In [75]:
import numpy as np 
import pandas as pd
from sklearn.preprocessing import LabelEncoder,OneHotEncoder,StandardScaler

In [76]:
df=pd.read_csv("train_df_1.csv")
df.drop(columns="ID",axis=1,inplace=True )
df.head(5)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20004 entries, 0 to 20003
Data columns (total 11 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   UNIXTime                20004 non-null  int64
 1   Data                    20004 non-null  object
 2   Time                    20004 non-null  object
 3   Radiation               20004 non-null  float64
 4   Temperature             18978 non-null  float64
 5   Pressure                18982 non-null  float64
 6   Humidity                18995 non-null  float64
 7   WindDirection(Degrees)  20004 non-null  float64
 8   Speed                   19055 non-null  float64
 9   TimeSunRise             20004 non-null  object
 10  TimeSunSet              20004 non-null  object
dtypes: float64(6), int64(1), object(4)
memory usage: 1.7+ MB

In [77]:
df["Datetime"] = pd.to_datetime(
    df["Data"] + " " + df["Time"],
    format="%d-%m-%Y %H:%M:%S"
)

In [78]:
df.head()

,UNIXTime,Data,Time,Radiation,Temperature,Pressure,Humidity,WindDirection(Degrees),Speed,TimeSunRise,TimeSunSet,Datetime
0,1477545019,26-10-2016,19:10:19,4.294954,48.0,30.41,93.0,124.57,11.25,06:21:00,17:52:00,2016-10-26 19:10:19
1,1477379721,24-10-2016,21:15:21,4.439169,47.0,30.47,81.0,148.63,5.62,06:21:00,17:53:00,2016-10-24 21:15:21
2,1477689619,28-10-2016,11:20:19,483.267515,51.0,30.42,100.0,19.15,3.37,06:22:00,17:51:00,2016-10-28 11:20:19
3,1476002422,08-10-2016,22:40:22,5.950979,50.0,30.43,90.0,189.05,5.62,06:15:00,18:05:00,2016-10-08 22:40:22
4,1477146317,22-10-2016,04:25:17,-8.324804,49.0,NaN,102.0,117.63,4.50,06:20:00,17:54:00,2016-10-22 04:25:17

In [79]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20004 entries, 0 to 20003
Data columns (total 12 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   UNIXTime                20004 non-null  int64
 1   Data                    20004 non-null  object
 2   Time                    20004 non-null  object
 3   Radiation               20004 non-null  float64
 4   Temperature             18978 non-null  float64
 5   Pressure                18982 non-null  float64
 6   Humidity                18995 non-null  float64
 7   WindDirection(Degrees)  20004 non-null  float64
 8   Speed                   19055 non-null  float64
 9   TimeSunRise             20004 non-null  object
 10  TimeSunSet              20004 non-null  object
 11  Datetime                20004 non-null  datetime64[ns]
dtypes: datetime64[ns](1), float64(6), int64(1), object(4)
memory usage: 1.8+ MB

In [80]:
df.head(5)

,UNIXTime,Data,Time,Radiation,Temperature,Pressure,Humidity,WindDirection(Degrees),Speed,TimeSunRise,TimeSunSet,Datetime
0,1477545019,26-10-2016,19:10:19,4.294954,48.0,30.41,93.0,124.57,11.25,06:21:00,17:52:00,2016-10-26 19:10:19
1,1477379721,24-10-2016,21:15:21,4.439169,47.0,30.47,81.0,148.63,5.62,06:21:00,17:53:00,2016-10-24 21:15:21
2,1477689619,28-10-2016,11:20:19,483.267515,51.0,30.42,100.0,19.15,3.37,06:22:00,17:51:00,2016-10-28 11:20:19
3,1476002422,08-10-2016,22:40:22,5.950979,50.0,30.43,90.0,189.05,5.62,06:15:00,18:05:00,2016-10-08 22:40:22
4,1477146317,22-10-2016,04:25:17,-8.324804,49.0,NaN,102.0,117.63,4.50,06:20:00,17:54:00,2016-10-22 04:25:17

In [81]:
df["hour"] = df["Datetime"].dt.hour
df["month"] = df["Datetime"].dt.month
df["day"] = df["Datetime"].dt.day
df["weekday"] = df["Datetime"].dt.weekday
df["year"] = df["Datetime"].dt.year
df.head(5)

,UNIXTime,Data,Time,Radiation,Temperature,Pressure,Humidity,WindDirection(Degrees),Speed,TimeSunRise,TimeSunSet,Datetime,hour,month,day,weekday,year
0,1477545019,26-10-2016,19:10:19,4.294954,48.0,30.41,93.0,124.57,11.25,06:21:00,17:52:00,2016-10-26 19:10:19,19,10,26,2,2016
1,1477379721,24-10-2016,21:15:21,4.439169,47.0,30.47,81.0,148.63,5.62,06:21:00,17:53:00,2016-10-24 21:15:21,21,10,24,0,2016
2,1477689619,28-10-2016,11:20:19,483.267515,51.0,30.42,100.0,19.15,3.37,06:22:00,17:51:00,2016-10-28 11:20:19,11,10,28,4,2016
3,1476002422,08-10-2016,22:40:22,5.950979,50.0,30.43,90.0,189.05,5.62,06:15:00,18:05:00,2016-10-08 22:40:22,22,10,8,5,2016
4,1477146317,22-10-2016,04:25:17,-8.324804,49.0,NaN,102.0,117.63,4.50,06:20:00,17:54:00,2016-10-22 04:25:17,4,10,22,5,2016

In [85]:
df.drop(columns=["Time","Datetime"],axis=1,inplace=True )

KeyError: "['Time', 'Datetime'] not found in axis"

In [88]:
df.drop(columns="Data",axis=1,inplace=True )

In [91]:
df["TimeSunRise"] = pd.to_datetime(df["TimeSunRise"])
df["TimeSunSet"] = pd.to_datetime(df["TimeSunSet"])

df["sunrise_hour"] = df["TimeSunRise"].dt.hour
df["sunset_hour"] = df["TimeSunSet"].dt.hour
df.drop(["TimeSunRise", "TimeSunSet"], axis=1, inplace=True)

KeyError: 'TimeSunRise'

In [93]:
df.drop("UNIXTime", axis=1, inplace=True)
df.head(5)

,Radiation,Temperature,Pressure,Humidity,WindDirection(Degrees),Speed,hour,month,day,weekday,year,sunrise_hour,sunset_hour
0,4.294954,48.0,30.41,93.0,124.57,11.25,19,10,26,2,2016,6,17
1,4.439169,47.0,30.47,81.0,148.63,5.62,21,10,24,0,2016,6,17
2,483.267515,51.0,30.42,100.0,19.15,3.37,11,10,28,4,2016,6,17
3,5.950979,50.0,30.43,90.0,189.05,5.62,22,10,8,5,2016,6,18
4,-8.324804,49.0,NaN,102.0,117.63,4.50,4,10,22,5,2016,6,17

In [102]:
df.drop(columns="year", axis=1, inplace=True)
df.isnull().sum()

Radiation                 0
Temperature               0
Pressure                  0
Humidity                  0
WindDirection(Degrees)    0
Speed                     0
hour                      0
month                     0
day                       0
weekday                   0
sunrise_hour              0
sunset_hour               0
dtype: int64

In [96]:
df.fillna(df.median(), inplace=True)

In [103]:
df.head(5)

,Radiation,Temperature,Pressure,Humidity,WindDirection(Degrees),Speed,hour,month,day,weekday,sunrise_hour,sunset_hour
0,4.294954,48.0,30.41,93.0,124.57,11.25,19,10,26,2,6,17
1,4.439169,47.0,30.47,81.0,148.63,5.62,21,10,24,0,6,17
2,483.267515,51.0,30.42,100.0,19.15,3.37,11,10,28,4,6,17
3,5.950979,50.0,30.43,90.0,189.05,5.62,22,10,8,5,6,18
4,-8.324804,49.0,30.43,102.0,117.63,4.50,4,10,22,5,6,17

In [104]:
df.to_csv("you_dataset.csv",index=False)