In [1]:
import numpy as np
from sklearn.model_selection import train_test_split,cross_val_score
from sklearn.linear_model import LogisticRegression

import pandas as pd
import seaborn as sns

In [2]:
df=pd.read_csv("train.csv",usecols=["Age","Pclass","SibSp","Parch","Survived"])
df.head()

   Survived  Pclass   Age  SibSp  Parch
0         0       3  22.0      1      0
1         1       1  38.0      1      0
2         1       3  26.0      0      0
3         1       1  35.0      1      0
4         0       3  35.0      0      0

In [3]:
df.isnull().sum()
df.dropna(inplace=True)
df.shape

(714, 5)

In [4]:
df.shape

(714, 5)

In [5]:
x=df.iloc[:,1:5]
x
y=df.iloc[:,0]
y

0      0
1      1
2      1
3      1
4      0
      ..
885    0
886    0
887    1
889    1
890    0
Name: Survived, Length: 714, dtype: int64

In [6]:
x.shape

(714, 4)

In [7]:
cross_val_score(LogisticRegression(),x,y,scoring="accuracy",cv=20).mean()

np.float64(0.6933333333333332)

In [8]:
x["Family_size"]=x["SibSp"]+x["Parch"]+1
x

     Pclass   Age  SibSp  Parch  Family_size
0         3  22.0      1      0            2
1         1  38.0      1      0            2
2         3  26.0      0      0            1
3         1  35.0      1      0            2
4         3  35.0      0      0            1
..      ...   ...    ...    ...          ...
885       3  39.0      0      5            6
886       2  27.0      0      0            1
887       1  19.0      0      0            1
889       1  26.0      0      0            1
890       3  32.0      0      0            1

[714 rows x 5 columns]

In [9]:
def family_class(num):
    if num==1:
        return 0
    elif num>=1 and num<=4:
        return 1
    else :
        return 2

In [10]:
x["family_type"]=x["Family_size"].apply(family_class)
x

     Pclass   Age  SibSp  Parch  Family_size  family_type
0         3  22.0      1      0            2            1
1         1  38.0      1      0            2            1
2         3  26.0      0      0            1            0
3         1  35.0      1      0            2            1
4         3  35.0      0      0            1            0
..      ...   ...    ...    ...          ...          ...
885       3  39.0      0      5            6            2
886       2  27.0      0      0            1            0
887       1  19.0      0      0            1            0
889       1  26.0      0      0            1            0
890       3  32.0      0      0            1            0

[714 rows x 6 columns]

In [11]:
x.drop(columns=["SibSp","Parch"],inplace=True)
x.head()

   Pclass   Age  Family_size  family_type
0       3  22.0            2            1
1       1  38.0            2            1
2       3  26.0            1            0
3       1  35.0            2            1
4       3  35.0            1            0

In [12]:
x.head()

   Pclass   Age  Family_size  family_type
0       3  22.0            2            1
1       1  38.0            2            1
2       3  26.0            1            0
3       1  35.0            2            1
4       3  35.0            1            0

In [13]:
cross_val_score(LogisticRegression(),x,y,scoring="accuracy",cv=20).mean()

np.float64(0.7046428571428571)

#Feature Splitting

In [14]:
df=pd.read_csv("train.csv")

In [15]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [16]:
df["Title"]=df["Name"].str.split(', ',expand=True)[1].str.split('.',expand=True)[0]

In [17]:
df['Name'].str.split(', ', expand=True)[1].str.split('.', expand=True)[0]

0        Mr
1       Mrs
2      Miss
3       Mrs
4        Mr
       ...
886     Rev
887    Miss
888    Miss
889      Mr
890      Mr
Name: 0, Length: 891, dtype: object

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
 12  Title        891 non-null    object
dtypes: float64(2), int64(5), object(6)
memory usage: 90.6+ KB

In [19]:
df[['Title','Name']]

    Title                                               Name
0      Mr                            Braund, Mr. Owen Harris
1     Mrs  Cumings, Mrs. John Bradley (Florence Briggs Th...
2    Miss                             Heikkinen, Miss. Laina
3     Mrs       Futrelle, Mrs. Jacques Heath (Lily May Peel)
4      Mr                           Allen, Mr. William Henry
..    ...                                                ...
886   Rev                              Montvila, Rev. Juozas
887  Miss                       Graham, Miss. Margaret Edith
888  Miss           Johnston, Miss. Catherine Helen "Carrie"
889    Mr                              Behr, Mr. Karl Howell
890    Mr                                Dooley, Mr. Patrick

[891 rows x 2 columns]

In [20]:
(df.groupby('Title')['Survived'].mean().sort_values(ascending=False))

Title
Lady            1.000000
Ms              1.000000
Sir             1.000000
Mme             1.000000
the Countess    1.000000
Mlle            1.000000
Mrs             0.792000
Miss            0.697802
Master          0.575000
Major           0.500000
Col             0.500000
Dr              0.428571
Mr              0.156673
Capt            0.000000
Jonkheer        0.000000
Don             0.000000
Rev             0.000000
Name: Survived, dtype: float64

In [29]:
df['Is_Married'] = 0
df.loc[df['Title']=='Mrs',"Is_Married"]=1

In [31]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Title,Is_Married
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,Mr,0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,Mrs,1
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,Miss,0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,Mrs,1
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,Mr,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,Rev,0
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,Miss,0
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,Miss,0
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,Mr,0
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,Mr,0